name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  linting-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run stylelint

      - name: Run Steiger
        run: npm run steiger

  build-check:
    runs-on: ubuntu-latest
    needs: linting-check
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
